### ISSUE TITLE
Error on run_on_cluster.sh

### ISSUE THREAD

**Issue by lmartinez2001** [g33kex/CoCPyT#1]
While running the command : ./run_on_cluster.sh --sync-only narval
mkdir is executed on the local machine instead of being executed on Compute Canada

**Comment by g33kex** [comment]
That script doesn't use mkdir
Did you follow the SSH Configuration section and made sure you can run `ssh narval`? 

If it still doesn't work, could you add set -x at the beginning of the script and paste the output?

**Comment by lmartinez2001** [comment]
![1](https://github.com/g33kex/CoCPyT/assets/17814218/2cc6e49f-c4fd-4a2a-9427-4f06496a89a1)

Here is what I get but I can't explain it at all. it's not supposed to have permission problems.

**Comment by g33kex** [comment]
The issue was caused by the username being different locally and on Compute Canada.
It was fixed in #3, please set the `USERNAME` variable in `config.sh` with your Computer Canada username.
