### ISSUE TITLE
Unexpected result after executing run_on_cluster.sh

### ISSUE THREAD

**Issue by lmartinez2001** [g33kex/CoCPyT#4]
On beluga, the ~/scratch/CoCPyT/ location only contains a .git folder, not the whole repo.

![1](https://github.com/g33kex/CoCPyT/assets/17814218/eaa4d7cf-11f8-4751-85a3-41b56f7313b1)

**Comment by yberreby** [comment]
Just did a clean setup and indeed. Simply missing a checkout step?

![1712787486_grim](https://github.com/g33kex/CoCPyT/assets/5556521/d7958c17-5cac-46dc-a2a1-68ccf9684a87)

**Comment by lmartinez2001** [comment]
The checkout worked. Thanks !

**Comment by yberreby** [comment]
This may still need addressing to prevent failure when simply following the instructions

**Comment by g33kex** [comment]
The checkout is skipped when using `--sync-only`. I think it makes sense to checkout automatically even in the `--sync-only` case though.
